import type { Metadata } from "next";
import type { ReactNode } from "react";
import { notFound } from "next/navigation";
import { canonical, jsonLD, missingMetadata, publicMetadata, summary } from "../../seo";
import { Avatar, Cover, PresenceLabel } from "../../media-components";
import Breadcrumbs from "../../breadcrumbs";
import { IconArrowRight, IconBriefcase, IconClock, IconStar, IconTag, IconUser, IconWallet } from "../../icons";
import { countLabel } from "../../russian-plural";

type Category={id:string;parent_id?:string;slug:string;name:string;description?:string;children?:Category[]};
type Freelancer={username:string;display_name:string;professional_title?:string;availability?:string;hourly_rate_kopecks?:number;skills?:{name:string}[];native_rating?:number;reviews_count?:number};
type Service={id:string;slug?:string;title:string;short_description?:string;service_type?:string;price_from?:{amount_kopecks:number};price_from_kopecks?:number;seller_username?:string;seller_display_name?:string;seller_native_rating?:number;seller_reviews_count?:number};
type Project={id:string;title:string;description:string;budget?:{min_kopecks?:number;max_kopecks?:number};deadline_at?:string;skills?:{name:string}[];customer_display_name?:string};
async function request(path:string){const base=process.env.API_BASE_URL??"http://localhost:8080";const r=await fetch(`${base}/api/v1${path}`,{cache:"no-store"});if(r.status===404)return null;if(!r.ok)return null;return r.json()}
function categoryPath(nodes:Category[],id:string,parents:Category[]=[]):Category[]|null{for(const node of nodes){const next=[...parents,node];if(node.id===id)return next;const nested=categoryPath(node.children??[],id,next);if(nested)return nested}return null}
async function load(slug:string){const category=(await request(`/categories/${encodeURIComponent(slug)}`))?.data as Category|undefined;if(!category)return null;const [treeResponse,freelancers,services,projects]=await Promise.all([request(`/categories`),request(`/freelancers?q=${encodeURIComponent(category.name)}&limit=6`),request(`/services?category=${category.id}&limit=6`),request(`/projects?category=${category.id}&limit=6`)]);const tree=(treeResponse?.data??[]) as Category[];const trail=categoryPath(tree,category.id)??[category];return{category,trail,freelancers:(freelancers?.data??[]) as Freelancer[],services:(services?.data??[]) as Service[],projects:(projects?.data??[]) as Project[]}}
const rub=(v?:number)=>v===undefined?"По договорённости":`${new Intl.NumberFormat("ru-RU").format(v/100)} ₽`;
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const data=await load(slug);if(!data)return missingMetadata("Категория не найдена");const thin=!data.freelancers.length&&!data.services.length&&!data.projects.length&&!data.category.children?.length;const metadata=publicMetadata(`${data.category.name}: специалисты, услуги и проекты`,summary(data.category.description,`Найдите специалистов, услуги и открытые проекты в направлении «${data.category.name}».`),`/categories/${data.category.slug}`);if(thin)metadata.robots={index:false,follow:true};return metadata}
export default async function CategoryPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const data=await load(slug);if(!data)notFound();const{category,trail,freelancers,services,projects}=data;const schema={"@context":"https://schema.org","@type":"CollectionPage",name:category.name,description:summary(category.description,`Публичный каталог направления ${category.name}.`),url:canonical(`/categories/${category.slug}`)};return <main className="category-detail-page">
<Breadcrumbs items={[{label:"Главная",href:"/"},{label:"Категории",href:"/categories"},...trail.slice(0,-1).map(item=>({label:item.name,href:`/categories/${item.slug}`})),{label:category.name}]}/>
<header className="category-detail-hero"><div><p className="eyebrow">Направление Naimio</p><h1>{category.name}</h1><p className="lead">{category.description||`Специалисты, услуги и открытые задачи в направлении «${category.name}».`}</p></div><div className="category-detail-hero__visual"><IconSpark category={category.name}/></div></header>
{category.children?.length?<section className="category-subsection"><div className="section-heading-row"><h2>Подкатегории</h2></div><div className="subcategory-pills">{category.children.map(v=><a key={v.id} href={`/categories/${v.slug}`}><IconTag size={16}/>{v.name}</a>)}</div></section>:null}
<CategorySection title="Специалисты" icon={<IconUser/>} count={freelancers.length} href={`/freelancers?q=${encodeURIComponent(category.name)}`}>
<div className="category-result-grid category-result-grid--talent">{freelancers.map(v=><a className="category-talent-card" key={v.username} href={`/freelancers/${v.username}`}><div className="category-card-top"><Avatar name={v.display_name} id={v.username} size="lg"/><span className="category-card-arrow"><IconArrowRight size={18}/></span></div><h3>{v.display_name}</h3><PresenceLabel id={v.username}/><p>{v.professional_title||"Специалист"}</p><div className="category-card-meta"><span><IconStar size={15}/>{v.native_rating?`${v.native_rating.toFixed(1)} · ${v.reviews_count??0}`:"Новый профиль"}</span>{v.hourly_rate_kopecks?<span><IconWallet size={15}/>{rub(v.hourly_rate_kopecks)}/ч</span>:null}</div>{v.skills?.length?<div className="category-card-chips">{v.skills.slice(0,3).map(s=><span key={s.name}>{s.name}</span>)}</div>:null}</a>)}</div>
</CategorySection>
<CategorySection title="Услуги" icon={<IconTag/>} count={services.length} href={`/services?category=${category.id}`}>
<div className="category-result-grid">{services.map(v=><a className="category-service-card" key={v.id} href={`/services/${v.slug||v.id}`}><Cover id={v.id} title={v.title} type={v.service_type}/><div className="category-service-card__body"><span className="category-kicker">{v.service_type?.replaceAll("_"," ")||"Услуга"}</span><h3>{v.title}</h3><p>{v.short_description||"Описание и условия доступны на странице услуги."}</p><div className="category-card-meta category-card-meta--seller"><span className="category-seller">{v.seller_username?<Avatar name={v.seller_display_name||v.seller_username} id={v.seller_username} size="sm"/>:null}<span>{v.seller_display_name||"Исполнитель Naimio"}<small>{v.seller_native_rating?`★ ${v.seller_native_rating.toFixed(1)} · ${countLabel(v.seller_reviews_count??0,["отзыв","отзыва","отзывов"])}`:"Новый профиль"}</small>{v.seller_username?<PresenceLabel id={v.seller_username}/>:null}</span></span><strong>{rub(v.price_from?.amount_kopecks??v.price_from_kopecks)}</strong></div></div></a>)}</div>
</CategorySection>
<CategorySection title="Открытые проекты" icon={<IconBriefcase/>} count={projects.length} href={`/projects?category=${category.id}`}>
<div className="category-project-list">{projects.map(v=><a className="category-project-card" key={v.id} href={`/projects/${v.id}`}><div><span className="category-kicker">{category.name}</span><h3>{v.title}</h3><p>{v.description}</p>{v.skills?.length?<div className="category-card-chips">{v.skills.slice(0,4).map(s=><span key={s.name}>{s.name}</span>)}</div>:null}</div><aside><span><IconWallet size={16}/>{v.budget?.max_kopecks?rub(v.budget.max_kopecks):v.budget?.min_kopecks?rub(v.budget.min_kopecks):"По договорённости"}</span>{v.deadline_at?<span><IconClock size={16}/>{new Intl.DateTimeFormat("ru-RU").format(new Date(v.deadline_at))}</span>:null}<b>Открыть <IconArrowRight size={16}/></b></aside></a>)}</div>
</CategorySection>
<div className="category-bottom-cta"><div><p className="eyebrow">Не нашли точное совпадение?</p><h2>Опишите задачу — Naimio поможет подобрать формат и специалистов.</h2></div><a className="button" href="/create-project">Разместить задачу</a></div>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLD(schema)}}/>
</main>}
function CategorySection({title,icon,count,href,children}:{title:string;icon:ReactNode;count:number;href:string;children:ReactNode}){return <section className="category-subsection"><div className="section-heading-row"><div className="section-heading-row__title"><span className="section-icon">{icon}</span><div><h2>{title}</h2><p>{count?`${count} ${count===1?"результат":"результатов"}`:"Пока нет результатов"}</p></div></div><a className="text-link" href={href}>Смотреть все <IconArrowRight size={16}/></a></div>{count?children:<div className="category-empty"><span className="section-icon">{icon}</span><div><strong>Пока ничего не найдено</strong><p>Попробуйте соседнее направление или вернитесь позже.</p></div></div>}</section>}
function IconSpark({category}:{category:string}){return <div className="category-orbit"><span>{category.slice(0,1).toUpperCase()}</span><i/><b/></div>}
