package acquisition

import "time"

func DefaultDefinitions() map[string]Definition {
	now := time.Date(2026, 8, 12, 0, 0, 0, 0, time.UTC)
	return map[string]Definition{
		"telegram-bot": {Slug: "telegram-bot", Title: "Стоимость Telegram-бота", Intro: "Оцените разработку Telegram-бота по функциям и интеграциям.", Version: 2, UpdatedAt: now, Questions: []Question{{Key: "complexity", Label: "Сценарий", Type: "SELECT", Required: true, Options: []Option{{"basic", "Простой информационный"}, {"workflow", "Бизнес-процесс"}, {"commerce", "Продажи и оплаты"}}}, {Key: "integrations", Label: "Количество интеграций", Type: "NUMBER", Required: true, Min: intp(0), Max: intp(10)}, {Key: "admin", Label: "Нужна панель управления", Type: "BOOLEAN", Required: true}}, Pricing: PricingConfig{BaselineMin: 3500000, BaselineMax: 8000000, DurationMin: 10, DurationMax: 25, OptionBasis: map[string]map[string]int{"complexity": {"basic": 0, "workflow": 2500, "commerce": 5000}}, NumberBasis: map[string]int{"integrations": 500}, BooleanBasis: map[string]int{"admin": 2500}, CategorySlug: "development", SkillSlugs: []string{"telegram", "backend"}, Assumptions: []string{"Готовый контент предоставляет заказчик", "Инфраструктура оплачивается отдельно"}}},
		"landing-page": {Slug: "landing-page", Title: "Стоимость лендинга", Intro: "Рассчитайте диапазон стоимости лендинга без ложной точности.", Version: 2, UpdatedAt: now, Questions: []Question{{Key: "design", Label: "Дизайн", Type: "SELECT", Required: true, Options: []Option{{"template", "На основе шаблона"}, {"custom", "Индивидуальный"}}}, {Key: "sections", Label: "Количество смысловых блоков", Type: "NUMBER", Required: true, Min: intp(3), Max: intp(20)}, {Key: "copywriting", Label: "Нужны тексты", Type: "BOOLEAN", Required: true}}, Pricing: PricingConfig{BaselineMin: 2500000, BaselineMax: 6000000, DurationMin: 7, DurationMax: 18, OptionBasis: map[string]map[string]int{"design": {"template": 0, "custom": 4000}}, NumberBasis: map[string]int{"sections": 200}, BooleanBasis: map[string]int{"copywriting": 2500}, CategorySlug: "development", SkillSlugs: []string{"frontend", "design"}, Assumptions: []string{"Одна языковая версия", "Без сложного личного кабинета"}}},
		"seo":          {Slug: "seo", Title: "Стоимость SEO-продвижения", Intro: "Оцените стартовый диапазон SEO-работ по размеру сайта и конкуренции.", Version: 2, UpdatedAt: now, Questions: []Question{{Key: "site_size", Label: "Размер сайта", Type: "SELECT", Required: true, Options: []Option{{"small", "До 50 страниц"}, {"medium", "50–500 страниц"}, {"large", "Более 500 страниц"}}}, {Key: "competition", Label: "Конкуренция", Type: "SELECT", Required: true, Options: []Option{{"low", "Низкая"}, {"medium", "Средняя"}, {"high", "Высокая"}}}, {Key: "content", Label: "Нужно производство контента", Type: "BOOLEAN", Required: true}}, Pricing: PricingConfig{BaselineMin: 2500000, BaselineMax: 6000000, DurationMin: 30, DurationMax: 90, OptionBasis: map[string]map[string]int{"site_size": {"small": 0, "medium": 2500, "large": 6000}, "competition": {"low": 0, "medium": 2000, "high": 5000}}, BooleanBasis: map[string]int{"content": 2500}, CategorySlug: "marketing", SkillSlugs: []string{"seo"}, Assumptions: []string{"Диапазон за первый этап работ", "Рекламный бюджет не включён"}}},
	}
}
func intp(v int) *int { return &v }
