"use client";

import { useCallback, useEffect, useState } from "react";
import Breadcrumbs from "../../breadcrumbs";
import FormattedText from "../../formatted-text";
import { useToast } from "../../toast";

type Service={id:string;title:string;status:string;moderation_status?:string;moderation_reason?:string;service_type:string;short_description?:string;updated_at:string};
const statusLabels:Record<string,string>={DRAFT:"Черновик",ACTIVE:"Опубликовано",PAUSED:"Приостановлено",REJECTED:"Нужны исправления",ARCHIVED:"В архиве"};
const typeLabels:Record<string,string>={PROFESSIONAL_SERVICE:"Услуга",CONSULTATION:"Консультация",EDUCATION:"Обучение",MENTORING:"Наставничество"};

export default function MyServices(){
  const[items,setItems]=useState<Service[]>([]);const[state,setState]=useState<"loading"|"ready"|"error">("loading");const{push}=useToast();
  const load=useCallback(()=>fetch("/api/v1/me/services",{credentials:"same-origin"}).then(response=>response.ok?response.json():Promise.reject()).then(body=>{setItems(body.data??[]);setState("ready")}).catch(()=>setState("error")),[]);
  useEffect(()=>{void load()},[load]);
  async function action(id:string,name:string){const response=await fetch(`/api/v1/me/services/${id}/${name}`,{method:"POST",credentials:"same-origin"});if(response.ok){await load();push({kind:"success",title:name==="publish"?"Предложение опубликовано":name==="pause"?"Предложение приостановлено":"Предложение снова активно"})}else push({kind:"error",title:"Не удалось изменить статус",message:"Проверьте данные предложения и состояние профессионального профиля."})}
  return <main><Breadcrumbs items={[{label:"Главная",href:"/"},{label:"Кабинет",href:"/dashboard"},{label:"Мои услуги"}]}/><div className="page-heading"><div><p className="eyebrow">Каталог</p><h1>Мои услуги</h1><p className="lead">Создавайте, редактируйте и публикуйте предложения без технических идентификаторов.</p></div><a className="button" href="/dashboard/services/new">Новое предложение</a></div>{state==="loading"?<div className="catalog-skeleton"><div className="skeleton"/><div className="skeleton"/></div>:state==="error"?<div className="error">Услуги не удалось загрузить. Обновите страницу и попробуйте ещё раз.</div>:items.length?<ul className="service-management-grid">{items.map(item=><li key={item.id}><article className="service-management-card"><div className="record__head"><span className="eyebrow">{typeLabels[item.service_type]||"Предложение"}</span><span className="badge">{statusLabels[item.status]||"Статус уточняется"}</span></div><h2>{item.title}</h2>{item.moderation_status==="HIDDEN"&&item.moderation_reason?<div className="notice notice--danger"><strong>Нужны исправления после модерации</strong><FormattedText value={item.moderation_reason}/></div>:null}{item.short_description?<p>{item.short_description}</p>:<p className="card-meta">Добавьте короткое описание, чтобы карточка была понятнее в каталоге.</p>}<div className="inline-actions">{item.status==="ACTIVE"?<><a className="button button--quiet button--compact" href={`/services/${item.id}`}>Открыть карточку</a><button className="button button--quiet button--compact" onClick={()=>void action(item.id,"pause")}>Приостановить</button></>:<><a className="button button--quiet button--compact" href={`/dashboard/services/${item.id}/edit`}>Редактировать</a>{item.status==="DRAFT"||item.status==="REJECTED"?<button className="button button--compact" onClick={()=>void action(item.id,"publish")}>Опубликовать</button>:item.status==="PAUSED"?<button className="button button--compact" onClick={()=>void action(item.id,"resume")}>Возобновить</button>:null}</>}</div></article></li>)}</ul>:<div className="empty"><h2>У вас ещё нет предложений</h2><p>Создайте консультацию, услугу, обучение или наставничество и опубликуйте её в каталоге.</p><a className="button" href="/dashboard/services/new">Создать предложение</a></div>}</main>
}
