"use client";
import { CustomSelect } from "../../custom-select";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useToast } from "../../toast";
import { createRandomID } from "../../random-id";

type Ref = { id: string; name: string; slug?: string };
type ExistingService = {
  id: string; category?: Ref; service_type: string; title: string; slug: string; short_description?: string; description: string;
  price_type: string; price_from?: { amount_kopecks: number }; delivery_days?: number; included_revisions?: number; visibility: string;
  skills?: Ref[]; media?: { id: string }[]; education_details?: { format: string; duration_minutes?: number; sessions_count?: number; audience_type?: string; group_size_max?: number };
};
type Props = { existing?: ExistingService; onSaved?: (id: string) => void };

const typeLabels: Record<string,string> = { PROFESSIONAL_SERVICE: "Профессиональная услуга", CONSULTATION: "Консультация", EDUCATION: "Обучение", MENTORING: "Наставничество" };
const translit:Record<string,string>={а:"a",б:"b",в:"v",г:"g",д:"d",е:"e",ё:"e",ж:"zh",з:"z",и:"i",й:"y",к:"k",л:"l",м:"m",н:"n",о:"o",п:"p",р:"r",с:"s",т:"t",у:"u",ф:"f",х:"h",ц:"ts",ч:"ch",ш:"sh",щ:"sch",ъ:"",ы:"y",ь:"",э:"e",ю:"yu",я:"ya"};
const slugFor=(value:string)=>value.toLowerCase().split("").map(char=>translit[char]??char).join("").normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,200)||"service";

export default function ServiceEditor({existing,onSaved}:Props){
  const {push}=useToast();
  const [categories,setCategories]=useState<Ref[]>([]);const[allSkills,setAllSkills]=useState<Ref[]>([]);const[skillQuery,setSkillQuery]=useState("");
  const [type,setType]=useState(existing?.service_type||"PROFESSIONAL_SERVICE");const[category,setCategory]=useState(existing?.category?.id||"");
  const [title,setTitle]=useState(existing?.title||"");const[shortDescription,setShortDescription]=useState(existing?.short_description||"");const[description,setDescription]=useState(existing?.description||"");
  const [priceType,setPriceType]=useState(existing?.price_type||"NEGOTIABLE");const[price,setPrice]=useState(existing?.price_from?String(existing.price_from.amount_kopecks/100):"");
  const [deliveryDays,setDeliveryDays]=useState(existing?.delivery_days?String(existing.delivery_days):"");const[revisions,setRevisions]=useState(existing?.included_revisions!==undefined?String(existing.included_revisions):"");
  const [visibility,setVisibility]=useState(existing?.visibility||"PUBLIC");const[skills,setSkills]=useState<string[]>(existing?.skills?.map(skill=>skill.id)||[]);
  const [format,setFormat]=useState(existing?.education_details?.format||"ONLINE");const[duration,setDuration]=useState(String(existing?.education_details?.duration_minutes||60));
  const [sessions,setSessions]=useState(String(existing?.education_details?.sessions_count||1));const[audience,setAudience]=useState(existing?.education_details?.audience_type||"INDIVIDUAL");
  const [groupSize,setGroupSize]=useState(String(existing?.education_details?.group_size_max||10));const[saving,setSaving]=useState(false);

  useEffect(()=>{Promise.all([fetch("/api/v1/categories"),fetch("/api/v1/skills?limit=100")]).then(async([c,s])=>Promise.all([c.ok?c.json():{data:[]},s.ok?s.json():{data:[]}])).then(([c,s])=>{const values:Ref[]=c.data??[];setCategories(values);setAllSkills(s.data??[]);setCategory(current=>current||values[0]?.id||"")}).catch(()=>push({kind:"error",title:"Не удалось загрузить категории и навыки"}));},[push]);
  const filteredSkills=useMemo(()=>allSkills.filter(skill=>!skillQuery||skill.name.toLowerCase().includes(skillQuery.toLowerCase())).slice(0,30),[allSkills,skillQuery]);
  const educational=type!=="PROFESSIONAL_SERVICE";
  function toggleSkill(id:string){setSkills(current=>current.includes(id)?current.filter(value=>value!==id):current.length<30?[...current,id]:current)}
  async function save(event:FormEvent){event.preventDefault();if(!category){push({kind:"error",title:"Выберите категорию"});return}if(priceType!=="NEGOTIABLE"&&(!price||Number(price)<=0)){push({kind:"error",title:"Укажите положительную цену"});return}setSaving(true);const education=educational?{format,duration_minutes:Number(duration),sessions_count:Number(sessions),audience_type:audience,group_size_max:audience==="GROUP"||audience==="BOTH"?Number(groupSize):null}:null;const payload={category_id:category,service_type:type,title:title.trim(),slug:existing?.slug||`${slugFor(title)}-${createRandomID().slice(0,6)}`,short_description:shortDescription.trim(),description:description.trim(),price_type:priceType,price_from:priceType==="NEGOTIABLE"?null:{amount_kopecks:Math.round(Number(price)*100),currency:"RUB"},delivery_days:deliveryDays?Number(deliveryDays):null,included_revisions:revisions!==""?Number(revisions):null,visibility,skill_ids:skills,media_object_ids:existing?.media?.map(item=>item.id)??[],education_details:education};try{const response=await fetch(existing?`/api/v1/me/services/${existing.id}`:"/api/v1/me/services",{method:existing?"PATCH":"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message||"Проверьте заполненные поля");push({kind:"success",title:existing?"Изменения сохранены":"Черновик предложения создан"});onSaved?.(body.data.id)}catch(error){push({kind:"error",title:"Не удалось сохранить предложение",message:error instanceof Error?error.message:"Попробуйте ещё раз."})}finally{setSaving(false)}}
  return <form className="project-editor service-editor" onSubmit={save}>
    <section className="form-section"><div className="form-section__heading"><span>01</span><div><h2>Предложение</h2><p>Выберите формат и кратко сформулируйте результат для заказчика.</p></div></div><div className="field-row"><label>Тип<CustomSelect value={type} onChange={event=>setType(event.target.value)}>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</CustomSelect></label><label>Категория<CustomSelect required value={category} onChange={event=>setCategory(event.target.value)}><option value="">Выберите категорию</option>{categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</CustomSelect></label></div><label>Название<input required minLength={3} maxLength={180} value={title} onChange={event=>setTitle(event.target.value)} placeholder="Например, аудит архитектуры Go API"/></label><label>Короткое описание<input maxLength={320} value={shortDescription} onChange={event=>setShortDescription(event.target.value)} placeholder="Что получит заказчик и для кого подходит предложение"/></label><label>Подробное описание<textarea required minLength={20} maxLength={10000} rows={8} value={description} onChange={event=>setDescription(event.target.value)} placeholder="Опишите состав результата, процесс работы и критерии готовности"/></label></section>
    <section className="form-section"><div className="form-section__heading"><span>02</span><div><h2>Цена и условия</h2><p>Укажите понятный ориентир без скрытых технических полей.</p></div></div><div className="field-row"><label>Тип цены<CustomSelect value={priceType} onChange={event=>setPriceType(event.target.value)}><option value="NEGOTIABLE">По договорённости</option><option value="FIXED">Фиксированная</option><option value="FROM">От указанной</option><option value="HOURLY">Почасовая</option></CustomSelect></label>{priceType!=="NEGOTIABLE"?<label>Цена, ₽<input required type="number" min="1" step="1" value={price} onChange={event=>setPrice(event.target.value)}/></label>:null}</div><div className="field-row"><label>Срок выполнения, дней<input type="number" min="1" max="365" value={deliveryDays} onChange={event=>setDeliveryDays(event.target.value)}/></label><label>Включено правок<input type="number" min="0" max="100" value={revisions} onChange={event=>setRevisions(event.target.value)}/></label><label>Видимость<CustomSelect value={visibility} onChange={event=>setVisibility(event.target.value)}><option value="PUBLIC">Показывать после публикации</option><option value="PRIVATE">Только по прямой ссылке</option></CustomSelect></label></div></section>
    {educational?<section className="form-section"><div className="form-section__heading"><span>03</span><div><h2>Формат проведения</h2><p>Параметры консультации, обучения или наставничества.</p></div></div><div className="field-row"><label>Проведение<CustomSelect value={format} onChange={event=>setFormat(event.target.value)}><option value="ONLINE">Онлайн</option><option value="OFFLINE">Очно</option><option value="ASYNC">Асинхронно</option><option value="HYBRID">Смешанно</option></CustomSelect></label><label>Продолжительность, минут<input required type="number" min="15" max="10080" step="15" value={duration} onChange={event=>setDuration(event.target.value)}/></label><label>Количество встреч<input required type="number" min="1" max="365" value={sessions} onChange={event=>setSessions(event.target.value)}/></label></div><div className="field-row"><label>Аудитория<CustomSelect value={audience} onChange={event=>setAudience(event.target.value)}><option value="INDIVIDUAL">Индивидуально</option><option value="GROUP">Группа</option><option value="BOTH">Оба формата</option></CustomSelect></label>{audience!=="INDIVIDUAL"?<label>Участников в группе<input required type="number" min="2" max="1000" value={groupSize} onChange={event=>setGroupSize(event.target.value)}/></label>:null}</div></section>:null}
    <section className="form-section"><div className="form-section__heading"><span>{educational?"04":"03"}</span><div><h2>Навыки</h2><p>Выберите до 30 навыков, по которым предложение смогут найти.</p></div></div><label>Найти навык<input type="search" value={skillQuery} onChange={event=>setSkillQuery(event.target.value)} placeholder="Go, Figma, аналитика…"/></label><div className="skill-picker" aria-label="Навыки">{filteredSkills.map(skill=><button className={skills.includes(skill.id)?"skill-option is-selected":"skill-option"} type="button" key={skill.id} onClick={()=>toggleSkill(skill.id)} aria-pressed={skills.includes(skill.id)}>{skill.name}</button>)}</div></section>
    <div className="project-editor__footer"><div><strong>{existing?"Сохраните изменения перед публикацией.":"Сначала создаётся черновик."}</strong><p>Предложение можно проверить и опубликовать из раздела «Мои услуги».</p></div><button disabled={saving}>{saving?"Сохраняем…":existing?"Сохранить изменения":"Сохранить черновик"}</button></div>
  </form>
}
