"use client";
import { CustomSelect } from "../../custom-select";
import Breadcrumbs from "../../breadcrumbs";
import FormattedText from "../../formatted-text";
import { FormEvent, useEffect, useState } from "react";
type Company={id:string;name:string};type Vacancy={id:string;title:string;status:string;moderation_status?:string;moderation_reason?:string;company?:Company};type Applicant={id:string;applicant_name:string;cover_message:string;status:string};
const vacancyStatus:Record<string,string>={DRAFT:"Черновик",PUBLISHED:"Опубликована",CLOSED:"Закрыта"};
const applicantStatus:Record<string,string>={NEW:"Новый",VIEWED:"Просмотрен",SHORTLISTED:"В шорт-листе",REJECTED:"Отклонён",HIRED:"Принят"};
export default function OwnerVacancies(){const[companies,setCompanies]=useState<Company[]>([]);const[items,setItems]=useState<Vacancy[]>([]);const[companyName,setCompanyName]=useState("");const[title,setTitle]=useState("");const[description,setDescription]=useState("");const[companyID,setCompanyID]=useState("");const[selected,setSelected]=useState("");const[apps,setApps]=useState<Applicant[]>([]);const[status,setStatus]=useState("");const load=()=>{fetch("/api/v1/me/companies").then(r=>r.ok?r.json():Promise.reject()).then(b=>setCompanies(b.data??[])).catch(()=>{});fetch("/api/v1/me/vacancies").then(r=>r.ok?r.json():Promise.reject()).then(b=>setItems(b.data??[])).catch(()=>setStatus("Не удалось загрузить вакансии."));};useEffect(load,[]);
async function addCompany(e:FormEvent){e.preventDefault();const slug=companyName.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||`company-${Date.now()}`;const r=await fetch("/api/v1/me/companies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:companyName,slug,website:"",description:""})});setStatus(r.ok?"Компания добавлена.":"Не удалось добавить компанию.");if(r.ok){setCompanyName("");load()}}
async function create(e:FormEvent){e.preventDefault();const slug=title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||`vacancy-${Date.now()}`;const r=await fetch("/api/v1/me/vacancies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({company_id:companyID,category_id:"",title,slug,description,employment_type:"FULL_TIME",salary_min_kopecks:null,salary_max_kopecks:null,currency:"RUB",location:"",remote:true,experience_level:"ANY",skill_ids:[]})});const body=await r.json().catch(()=>null);setStatus(r.ok?"Черновик вакансии создан.":body?.error?.message||"Не удалось создать вакансию.");if(r.ok){setTitle("");setDescription("");load()}}
async function action(id:string,name:string){const r=await fetch(`/api/v1/me/vacancies/${id}/${name}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});setStatus(r.ok?"Статус вакансии обновлён.":"Переход статуса недоступен.");if(r.ok)load()}
async function applicants(id:string){setSelected(id);const r=await fetch(`/api/v1/me/vacancies/${id}/applications`);if(r.ok)setApps((await r.json()).data??[]);else setStatus("Нет доступа к откликам.")}
async function appStatus(app:string,next:string){const r=await fetch(`/api/v1/me/vacancies/${selected}/applications/${app}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:next})});if(r.ok)applicants(selected);else setStatus("Не удалось изменить статус отклика.")}
return <main>
  <Breadcrumbs items={[{label:"Главная",href:"/"},{label:"Кабинет",href:"/dashboard"},{label:"Мои вакансии"}]}/>
  <header className="page-heading"><div><h1>Мои вакансии</h1><p className="card-meta">Создавайте компании, публикуйте вакансии и ведите отклики кандидатов.</p></div></header>
  {status?<p role="status" className="notice">{status}</p>:null}
  <section className="deal-panel"><h2>Компания</h2><form className="stacked-form" onSubmit={addCompany}><label>Название <input maxLength={180} required value={companyName} onChange={e=>setCompanyName(e.target.value)}/></label><button>Добавить компанию</button></form></section>
  <section className="deal-panel"><h2>Новая вакансия</h2><form className="stacked-form" onSubmit={create}>
    <label>Компания <CustomSelect value={companyID} onChange={e=>setCompanyID(e.target.value)}><option value="">Без компании</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</CustomSelect></label>
    <label>Название <input maxLength={200} required value={title} onChange={e=>setTitle(e.target.value)}/></label>
    <label>Описание<textarea maxLength={20000} required rows={6} value={description} onChange={e=>setDescription(e.target.value)}/></label>
    <button>Сохранить черновик</button>
  </form></section>
  <section className="deal-panel"><h2>Вакансии</h2>{items.length===0?<p className="empty">Черновиков пока нет.</p>:<ul className="record-list">{items.map(v=><li key={v.id} className="record"><div className="record__head"><strong>{v.title}</strong><span className={`badge${v.moderation_status==="HIDDEN"?" badge--danger":""}`}>{v.moderation_status==="HIDDEN"?"Отклонена модерацией":(vacancyStatus[v.status]??v.status)}</span></div>{v.moderation_status==="HIDDEN"&&v.moderation_reason?<div className="notice notice--danger"><FormattedText value={v.moderation_reason}/></div>:null}<div className="inline-actions">{v.status==="DRAFT"?<><a className="button button--quiet" href={`/dashboard/vacancies/${v.id}/edit`}>Редактировать</a><button className="button button--quiet" onClick={()=>action(v.id,"publish")}>Опубликовать</button></>:null}{v.status==="PUBLISHED"&&v.moderation_status!=="HIDDEN"?<button className="button button--quiet" onClick={()=>action(v.id,"close")}>Закрыть</button>:null}{v.status==="PUBLISHED"&&v.moderation_status!=="HIDDEN"?<button className="button button--quiet" onClick={()=>applicants(v.id)}>Отклики</button>:null}</div></li>)}</ul>}</section>
  {selected?<div className="modal-backdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)setSelected("")}}><section className="modal-card vacancy-applicants-modal" role="dialog" aria-modal="true" aria-labelledby="vacancy-applicants-title"><div className="modal-card__header"><div><p className="eyebrow">Моя вакансия</p><h2 id="vacancy-applicants-title">Отклики</h2></div><button type="button" className="modal-close" aria-label="Закрыть" onClick={()=>setSelected("")}>×</button></div>{apps.length===0?<p className="empty">Откликов пока нет.</p>:<ul className="record-list">{apps.map(a=><li key={a.id} className="record"><div className="record__head"><strong>{a.applicant_name}</strong><span className="badge">{applicantStatus[a.status]??a.status}</span></div><p className="record__body">{a.cover_message}</p><div className="inline-actions"><button className="button button--quiet" onClick={()=>appStatus(a.id,"VIEWED")}>Просмотрен</button><button className="button button--quiet" onClick={()=>appStatus(a.id,"SHORTLISTED")}>В шорт-лист</button><button className="button button--quiet" onClick={()=>appStatus(a.id,"REJECTED")}>Отклонить</button></div></li>)}</ul>}</section></div>:null}
</main>;
}
