"use client";
import { useCallback, useEffect, useState } from "react";
import { Avatar, Cover, PresenceLabel } from "../media-components";
import Breadcrumbs from "../breadcrumbs";
import { IconArrowRight, IconBriefcase, IconHeart, IconStar, IconTag, IconUser, IconWallet } from "../icons";
import { countLabel } from "../russian-plural";
import { FavoritesSkeleton } from "../skeletons";
type Favorite={entity_type:"FREELANCER"|"SERVICE"|"PROJECT";entity_id:string;created_at:string;title?:string;subtitle?:string;username?:string;slug?:string;category?:string;amount_kopecks?:number;rating?:number;reviews_count?:number};
const tabs=["FREELANCER","SERVICE","PROJECT"] as const;const labels={FREELANCER:"Специалисты",SERVICE:"Услуги",PROJECT:"Проекты"};
const rub=(v?:number)=>v===undefined?"По договорённости":`${new Intl.NumberFormat("ru-RU").format(v/100)} ₽`;
export default function FavoritesPage(){const[type,setType]=useState<(typeof tabs)[number]>("FREELANCER");const[items,setItems]=useState<Favorite[]>([]);const[loading,setLoading]=useState(true);const[failed,setFailed]=useState(false);const load=useCallback(async()=>{setLoading(true);setFailed(false);try{const r=await fetch(`/api/v1/me/favorites?type=${type}`);if(!r.ok)throw new Error();const b=await r.json();setItems(b.data??[])}catch{setItems([]);setFailed(true)}finally{setLoading(false)}},[type]);useEffect(()=>{void load()},[load]);async function remove(item:Favorite){const previous=items;setItems(v=>v.filter(x=>x.entity_id!==item.entity_id));const r=await fetch(`/api/v1/me/favorites/${item.entity_type}/${item.entity_id}`,{method:"DELETE"});if(!r.ok)setItems(previous)}return <main className="favorites-page"><Breadcrumbs items={[{label:"Главная",href:"/"},{label:"Избранное"}]}/><header className="favorites-hero"><div><p className="eyebrow">Ваши сохранения</p><h1>Избранное</h1><p className="lead">Лёгкие закладки для быстрого возврата. Постоянных исполнителей добавляйте в «Мою команду».</p></div><span className="favorites-hero__icon"><IconHeart size={34}/></span></header><div className="favorites-tabs" role="tablist" aria-label="Тип избранного">{tabs.map(tab=><button key={tab} role="tab" aria-selected={type===tab} onClick={()=>setType(tab)}>{tab==="FREELANCER"?<IconUser size={18}/>:tab==="SERVICE"?<IconTag size={18}/>:<IconBriefcase size={18}/>} {labels[tab]}</button>)}</div>{loading?<FavoritesSkeleton count={6}/>:failed?<div className="error">Не удалось загрузить избранное. Попробуйте обновить страницу.</div>:items.length?<div className="favorites-grid">{items.map(item=><FavoriteCard key={`${item.entity_type}:${item.entity_id}`} item={item} remove={()=>void remove(item)}/>)}</div>:<div className="favorites-empty"><span><IconHeart size={30}/></span><h2>Здесь пока ничего нет</h2><p>{type==="FREELANCER"?"Сохраняйте понравившихся специалистов, чтобы быстро вернуться к ним.":type==="SERVICE"?"Добавляйте подходящие услуги в избранное для сравнения.":"Сохраняйте интересные проекты и возвращайтесь к ним позже."}</p><a className="button button--secondary" href={type==="FREELANCER"?"/freelancers":type==="SERVICE"?"/services":"/projects"}>Перейти в каталог</a></div>}</main>}
function FavoriteCard({item,remove}:{item:Favorite;remove:()=>void}){const href=item.entity_type==="FREELANCER"?`/freelancers/${item.username||""}`:item.entity_type==="SERVICE"?`/services/${item.slug||item.entity_id}`:`/projects/${item.slug||item.entity_id}`;return <article className={`favorite-card favorite-card--${item.entity_type.toLowerCase()}`}>{item.entity_type==="SERVICE"?<Cover id={item.entity_id} title={item.title||"Услуга"}/>:null}<div className="favorite-card__body"><div className="favorite-card__head">{item.entity_type==="FREELANCER"?<Avatar name={item.title||"Специалист"} id={item.username||item.entity_id} size="lg"/>:<span className="section-icon">{item.entity_type==="PROJECT"?<IconBriefcase/>:<IconTag/>}</span>}<button className="icon-button icon-button--danger" onClick={remove} aria-label="Удалить из избранного"><IconHeart size={18}/></button></div><p className="category-kicker">{item.category||labels[item.entity_type]}</p><h2><a href={href}>{item.title||labels[item.entity_type]}</a></h2>{item.subtitle?<p className="favorite-card__desc">{item.subtitle}</p>:null}<div className="favorite-card__meta">{item.entity_type==="FREELANCER"?<><span><IconStar size={15}/>{item.rating?`${item.rating.toFixed(1)} · ${countLabel(item.reviews_count??0,["отзыв","отзыва","отзывов"])}`:"Новый профиль"}</span><PresenceLabel id={item.username||item.entity_id}/></>:null}{item.amount_kopecks!==undefined?<strong className="catalog-price"><IconWallet size={15}/>{rub(item.amount_kopecks)}{item.entity_type==="FREELANCER"?"/ч":""}</strong>:null}</div><a className="card-link" href={href}>Открыть <IconArrowRight size={16}/></a></div></article>}
