"use client";
import { CustomSelect } from "../../../custom-select";
import Breadcrumbs from "../../../breadcrumbs";
import { use, FormEvent, useCallback, useEffect, useState } from "react";
import ReviewForm from "../../../review-form";
import { createRandomID } from "../../../random-id";
import { useToast } from "../../../toast";
import { SafeDealSkeleton } from "../../../skeletons";

type Alloc={total_kopecks:number;customer_kopecks:number;freelancer_kopecks:number;platform_kopecks:number};
type Quote={currency:string;work_amount_kopecks:number;platform_fee:Alloc;provider_fee:Alloc;customer_discount_kopecks:number;freelancer_bonus_kopecks:number;customer_total_kopecks:number;freelancer_payout_kopecks:number};
type Deal={id:string;project_id:string;project_title?:string;counterparty_name?:string;gross_amount_kopecks:number;platform_fee_kopecks:number;freelancer_amount_kopecks:number;quote?:Quote;status:string;viewer_role:"CUSTOMER"|"FREELANCER";payment?:{provider:string;provider_status:string;checkout_url?:string};submission?:{summary:string};dispute?:{id:string;reason_code:string;description:string;status:string};evidence?:Array<{id:string;kind:string;body:string}>;conversation_id?:string;provider_capability_notice?:string};
const money=(n:number)=>new Intl.NumberFormat("ru-RU",{minimumFractionDigits:0,maximumFractionDigits:2}).format(n/100)+" ₽";
// financeStatusText explains the money state in production wording — never the
// raw payment-provider name or status code (e.g. "sandbox · FUNDED").
const financeStatusText:Record<string,string>={AWAITING_FUNDING:"Ожидает оплаты заказчиком — средства ещё не зарезервированы.",FUNDED:"Средства зарезервированы на безопасном счёте и будут переведены исполнителю после приёмки работы.",IN_PROGRESS:"Средства зарезервированы на безопасном счёте до приёмки работы.",SUBMITTED:"Средства зарезервированы. Ожидается приёмка работы заказчиком.",REVISION_REQUESTED:"Средства остаются зарезервированными на время доработки.",DISPUTED:"Средства заморожены до разрешения спора.",ACCEPTED:"Работа принята — выполняется перевод средств исполнителю.",RELEASE_PENDING:"Выполняется перевод средств исполнителю.",COMPLETED:"Средства переведены исполнителю, сделка завершена.",CANCEL_PENDING:"Отмена сделки — средства возвращаются заказчику.",CANCELED:"Сделка отменена, средства не были переданы исполнителю.",REFUND_PENDING:"Выполняется возврат средств заказчику.",REFUNDED:"Средства возвращены заказчику.",FAILED:"Произошёл сбой платёжной операции — обратитесь в поддержку."};
// Breakdown renders a transparent, role-aware money split from the deal's
// authoritative quote snapshot. The customer sees only the rows they actually
// pay; the freelancer sees what is deducted from the project amount. The final
// figure always comes from the backend quote — the UI never recomputes money.
function Breakdown({d}:{d:Deal}){
  const q=d.quote;const isCustomer=d.viewer_role==="CUSTOMER";
  if(!q||!q.customer_total_kopecks){return <section className="deal-money-grid"><article><span>{isCustomer?"К оплате":"Сумма проекта"}</span><strong>{money(d.gross_amount_kopecks)}</strong></article><article><span>Комиссия сервиса</span><strong>{money(d.platform_fee_kopecks)}</strong></article><article><span>{isCustomer?"Исполнителю":"Вы получите"}</span><strong>{money(d.freelancer_amount_kopecks)}</strong></article></section>;}
  if(isCustomer){const feePayer=(a:Alloc)=>a.customer_kopecks>0&&a.freelancer_kopecks>0?"распределена между заказчиком и исполнителем":a.customer_kopecks>0?"оплачиваете вы":a.freelancer_kopecks>0?"удерживается из выплаты исполнителя":"оплачивает платформа";return <details className="deal-breakdown" open><summary><span>К оплате</span><strong>{money(q.customer_total_kopecks)}</strong></summary><div className="deal-breakdown__rows"><div className="deal-breakdown__row"><span>Стоимость работы</span><span>{money(q.work_amount_kopecks)}</span></div>{q.platform_fee.total_kopecks>0?<div className="deal-breakdown__row"><span>Комиссия сервиса <small>({feePayer(q.platform_fee)})</small></span><span>{money(q.platform_fee.total_kopecks)}</span></div>:null}{q.provider_fee.total_kopecks>0?<div className="deal-breakdown__row"><span>Комиссия платёжного провайдера <small>({feePayer(q.provider_fee)})</small></span><span>{money(q.provider_fee.total_kopecks)}</span></div>:null}{q.customer_discount_kopecks>0?<div className="deal-breakdown__row deal-breakdown__row--credit"><span>Скидка</span><span>−{money(q.customer_discount_kopecks)}</span></div>:null}<div className="deal-breakdown__row deal-breakdown__row--total"><span>К оплате заказчиком</span><strong>{money(q.customer_total_kopecks)}</strong></div><div className="deal-breakdown__row"><span>Исполнитель получит после комиссий</span><strong>{money(q.freelancer_payout_kopecks)}</strong></div></div><p className="deal-breakdown__note">Комиссии показаны полностью с указанием, кто их оплачивает. Сумма к оплате и выплата исполнителю зафиксированы в условиях Безопасной сделки.</p></details>;}
  return <details className="deal-breakdown" open><summary><span>Вы получите</span><strong>{money(q.freelancer_payout_kopecks)}</strong></summary><div className="deal-breakdown__rows"><div className="deal-breakdown__row"><span>Стоимость проекта</span><span>{money(q.work_amount_kopecks)}</span></div>{q.platform_fee.freelancer_kopecks>0?<div className="deal-breakdown__row deal-breakdown__row--debit"><span>Комиссия сервиса</span><span>−{money(q.platform_fee.freelancer_kopecks)}</span></div>:null}{q.provider_fee.freelancer_kopecks>0?<div className="deal-breakdown__row deal-breakdown__row--debit"><span>Safe Deal · оплата</span><span>−{money(q.provider_fee.freelancer_kopecks)}</span></div>:null}{q.freelancer_bonus_kopecks>0?<div className="deal-breakdown__row deal-breakdown__row--credit"><span>Бонус</span><span>+{money(q.freelancer_bonus_kopecks)}</span></div>:null}<div className="deal-breakdown__row deal-breakdown__row--total"><span>Вы получите</span><strong>{money(q.freelancer_payout_kopecks)}</strong></div></div><p className="deal-breakdown__note">Сумма к выплате зафиксирована при создании сделки и не изменится. Перевод выполняется после приёмки работы заказчиком.</p></details>;
}
const commandKey=()=>createRandomID();
const statusText:Record<string,string>={AWAITING_FUNDING:"Ожидает оплаты",FUNDED:"Финансирование подтверждено",IN_PROGRESS:"В работе",SUBMITTED:"Работа передана",REVISION_REQUESTED:"На доработке",DISPUTED:"Открыт спор",ACCEPTED:"Работа принята",RELEASE_PENDING:"Расчёт выполняется",COMPLETED:"Завершена",CANCEL_PENDING:"Отмена выполняется",CANCELED:"Отменена",REFUND_PENDING:"Возврат выполняется",REFUNDED:"Возврат выполнен",FAILED:"Ошибка"};
// Dispute enums are also rendered in Russian — never as raw codes like OPEN / WORK_NOT_DELIVERED / COMMENT.
const disputeStatusText:Record<string,string>={OPEN:"Открыт",EVIDENCE_COLLECTION:"Сбор материалов",UNDER_REVIEW:"На рассмотрении",RESOLVED_CUSTOMER:"Решён в пользу заказчика",RESOLVED_FREELANCER:"Решён в пользу исполнителя",RESOLVED_SPLIT:"Решён 50/50",DISMISSED:"Отклонён"};
const reasonText:Record<string,string>={WORK_NOT_DELIVERED:"Работа не передана",WORK_DOES_NOT_MATCH_SCOPE:"Результат не соответствует заданию",CUSTOMER_UNRESPONSIVE:"Заказчик не отвечает",OTHER:"Другое"};
const evidenceKindText:Record<string,string>={COMMENT:"Комментарий",FILE:"Файл",LINK:"Ссылка"};
const confirmText:Record<string,string>={fund:"Создать запрос на оплату и зарезервировать средства по сделке?",accept:"Принять работу? После приёмки средства будут направлены исполнителю, и отменить это будет нельзя.",cancel:"Отменить сделку? Действие необратимо.",disputes:"Открыть спор? Автоматический расчёт будет приостановлен до решения спора."};
const FLOW:Array<[string,string]>=[["AWAITING_FUNDING","Финансирование"],["FUNDED","Средства зарезервированы"],["IN_PROGRESS","В работе"],["SUBMITTED","Результат передан"],["ACCEPTED","Принято"],["COMPLETED","Завершено"]];
const stepOf:Record<string,number>={AWAITING_FUNDING:0,CANCEL_PENDING:0,CANCELED:0,FAILED:0,FUNDED:1,REFUND_PENDING:1,REFUNDED:1,IN_PROGRESS:2,REVISION_REQUESTED:2,SUBMITTED:3,DISPUTED:3,ACCEPTED:4,RELEASE_PENDING:4,COMPLETED:5};
async function alreadyReviewed(projectID:string){let cursor="";for(let page=0;page<20;page++){const query=new URLSearchParams({limit:"50"});if(cursor)query.set("cursor",cursor);const response=await fetch(`/api/v1/me/reviews/given?${query}`,{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw new Error("review history unavailable");const body=await response.json();if((body.data??[]).some((item:{project_id?:string})=>item.project_id===projectID))return true;cursor=body.page?.next_cursor??"";if(!cursor)return false;}return false;}

export default function DealPage({params}:{params:Promise<{id:string}>}){const { id } = use(params);const { push }=useToast();
  const[d,setDeal]=useState<Deal|null>(null),[state,setState]=useState("Загрузка…"),[summary,setSummary]=useState(""),[revision,setRevision]=useState(""),[reason,setReason]=useState(""),[description,setDescription]=useState(""),[evidence,setEvidence]=useState("");
  const[reviewState,setReviewState]=useState<"idle"|"loading"|"available"|"given"|"error">("idle");
  const load=useCallback(()=>fetch(`/api/v1/me/safe-deals/${id}`,{credentials:"same-origin"}).then(async r=>{if(r.status===401){location.assign(`/login?next=${encodeURIComponent(location.pathname)}`);return null}if(!r.ok)throw new Error();return r.json()}).then(b=>{setDeal(b?.data??null);setState(b?.data?"":"Сделка не найдена.")}),[id]);
  useEffect(()=>{load().catch(()=>setState("Не удалось загрузить сделку."))},[load]);
  const paymentPresent=Boolean(d?.payment);
  const paymentProviderStatus=d?.payment?.provider_status;
  useEffect(()=>{if(!paymentPresent||!d?.status||!["AWAITING_FUNDING","RELEASE_PENDING","REFUND_PENDING","CANCEL_PENDING"].includes(d.status))return;let active=true;let attempts=0;const timer=setInterval(()=>{if(!active||attempts++>=20){clearInterval(timer);return}load().catch(()=>undefined)},2000);return()=>{active=false;clearInterval(timer)}},[paymentPresent,paymentProviderStatus,d?.status,load]);
  useEffect(()=>{if(!d||d.status!=="COMPLETED"){setReviewState("idle");return}let active=true;setReviewState("loading");alreadyReviewed(d.project_id).then((given)=>{if(active)setReviewState(given?"given":"available")}).catch(()=>{if(active)setReviewState("error")});return()=>{active=false}},[d]);
  async function action(name:string,body:unknown={}){if(confirmText[name]&&!confirm(confirmText[name]))return;const r=await fetch(`/api/v1/me/safe-deals/${id}/${name}`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","Idempotency-Key":commandKey()},body:JSON.stringify(body)});const b=await r.json().catch(()=>null);if(!r.ok){const code=b?.error?.code;const message=code==="PAYMENT_PROVIDER_UNAVAILABLE"?"Платёжный провайдер сейчас недоступен. Обновите страницу и повторите попытку.":b?.error?.message??"Действие недоступно.";push({kind:"error",title:"Не удалось выполнить действие",message});return}setDeal(b.data);push({kind:"success",title:name==="fund"&&b?.data?.status==="FUNDED"?"Тестовая оплата подтверждена":name==="fund"?"Оплата подготовлена":"Готово"});if(name==="fund"&&b?.data?.payment?.checkout_url){location.assign(b.data.payment.checkout_url)}}
  async function addEvidence(){if(!d?.dispute)return;const r=await fetch(`/api/v1/me/safe-deals/disputes/${d.dispute.id}/evidence`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","Idempotency-Key":commandKey()},body:JSON.stringify({kind:"COMMENT",body:evidence})});if(!r.ok){push({kind:"error",title:"Не удалось добавить материал"});return}push({kind:"success",title:"Материал добавлен"});setEvidence("");load()}
  if(!d)return <main><Breadcrumbs items={[{label:"Главная",href:"/"},{label:"Кабинет",href:"/dashboard"},{label:"Безопасные сделки",href:"/dashboard/safe-deals"},{label:"Сделка"}]}/>{state && state !== "Загрузка…" ? <p role="status" className="notice notice--error">{state}</p> : <SafeDealSkeleton/>}</main>;
  const disputable=["FUNDED","IN_PROGRESS","SUBMITTED","REVISION_REQUESTED"].includes(d.status);
  return <main>
    <Breadcrumbs items={[{label:"Главная",href:"/"},{label:"Кабинет",href:"/dashboard"},{label:"Безопасные сделки",href:"/dashboard/safe-deals"},{label:"Сделка"}]}/>
    <header className="deal-hero"><div><p className="eyebrow">Safe Deal · {statusText[d.status]??d.status}</p><h1>{d.project_title||"Безопасная сделка"}</h1><p>{d.counterparty_name?`${d.viewer_role==="CUSTOMER"?"Исполнитель":"Заказчик"}: ${d.counterparty_name} · `:""}<a className="admin-primary-link" href={d.viewer_role==="CUSTOMER"?`/dashboard/projects/${d.project_id}`:`/projects/${d.project_id}`}>Открыть проект →</a></p></div><span className="badge badge--success">{d.viewer_role==="CUSTOMER"?"Вы заказчик":"Вы исполнитель"}</span></header>
    <div className="deal-layout"><div className="deal-main">
      <section className="deal-panel"><h2>Ход сделки</h2><ol className="deal-timeline" aria-label="Этапы сделки">{FLOW.map(([code,label],i)=>{const cur=stepOf[d.status]??0;const done=i<cur||d.status==="COMPLETED";return <li key={code} className={done?"is-done":i===cur?"is-active":"is-todo"}><span className="deal-timeline__dot"/><span className="deal-timeline__label">{label}</span></li>;})}</ol>{d.status==="DISPUTED"?<p className="deal-banner deal-banner--danger">Открыт спор — автоматический расчёт приостановлен до решения.</p>:null}{d.status==="REVISION_REQUESTED"?<p className="deal-banner deal-banner--warning">Заказчик запросил доработку — результат вернулся исполнителю.</p>:null}{["CANCELED","CANCEL_PENDING"].includes(d.status)?<p className="deal-banner deal-banner--warning">Сделка отменяется — средства не были переданы исполнителю.</p>:null}{["REFUNDED","REFUND_PENDING"].includes(d.status)?<p className="deal-banner deal-banner--warning">Оформлен возврат средств заказчику.</p>:null}{d.status==="FAILED"?<p className="deal-banner deal-banner--danger">Операция завершилась ошибкой — обратитесь в поддержку.</p>:null}</section>
      <Breakdown d={d}/>
      <section className="deal-panel"><h2>Финансовый статус</h2><p>{financeStatusText[d.status]??"Финансовое состояние обновляется после подтверждения оплаты."}</p></section>
      {d.viewer_role==="CUSTOMER"&&d.status==="SUBMITTED"?<section className="deal-panel"><p className="eyebrow">Переданный результат</p><h2>Работа ожидает решения</h2><p>{d.submission?.summary||"Исполнитель передал результат."}</p><div className="inline-actions"><button onClick={()=>action("accept")}>Принять работу</button></div><form className="deal-embedded-form" onSubmit={(e:FormEvent)=>{e.preventDefault();action("revision",{reason:revision})}}><label>Что нужно доработать<textarea required maxLength={2000} value={revision} onChange={e=>setRevision(e.target.value)}/></label><button className="button button--quiet">Запросить доработку</button></form></section>:null}
      {d.viewer_role==="FREELANCER"&&["IN_PROGRESS","REVISION_REQUESTED"].includes(d.status)?<section className="deal-panel"><p className="eyebrow">Передача результата</p><h2>Отправить работу заказчику</h2><form className="deal-embedded-form" onSubmit={(e:FormEvent)=>{e.preventDefault();action("submit",{summary})}}><label>Что передано заказчику<textarea required maxLength={5000} value={summary} onChange={e=>setSummary(e.target.value)}/></label><button>Передать работу</button></form></section>:null}
      {d.status==="COMPLETED"?<section className="deal-panel"><p className="eyebrow">Отзыв о сотрудничестве</p>{reviewState==="loading"?<p>Проверяем историю отзывов…</p>:reviewState==="given"?<><h2>Отзыв уже опубликован</h2><p>Вы уже оценили эту сделку. Повторный отзыв по тому же проекту недоступен.</p><a className="button button--quiet" href="/dashboard/reviews">Мои отзывы</a></>:reviewState==="available"?<><h2>Оцените завершённую сделку</h2><p>Сделка завершена — теперь вы можете оставить отзыв о второй стороне. Он публикуется в её профиле и учитывается в рейтинге на платформе.</p><ReviewForm projectId={d.project_id} role={d.viewer_role} onSuccess={()=>setReviewState("given")}/></>:<p>Не удалось проверить историю отзывов. Обновите страницу перед публикацией отзыва.</p>}</section>:null}
      {d.dispute?<section className="deal-panel deal-panel--danger"><p className="eyebrow">Спор</p><h2>{disputeStatusText[d.dispute.status]??d.dispute.status}</h2><p><strong>{reasonText[d.dispute.reason_code]??d.dispute.reason_code}</strong></p><p>{d.dispute.description}</p>{d.evidence?.length?<ul className="deal-evidence">{d.evidence.map(v=><li key={v.id}><strong>{evidenceKindText[v.kind]??v.kind}</strong><p>{v.body}</p></li>)}</ul>:null}{d.dispute.status==="OPEN"?<form className="deal-embedded-form" onSubmit={(event:FormEvent)=>{event.preventDefault();addEvidence()}}><label>Добавить материал<textarea required maxLength={5000} value={evidence} onChange={event=>setEvidence(event.target.value)}/></label><button>Добавить к спору</button></form>:null}</section>:null}
      {disputable&&!d.dispute?<section className="deal-panel"><details><summary><strong>Возникла проблема?</strong> Открыть спор</summary><form className="deal-embedded-form" onSubmit={(e:FormEvent)=>{e.preventDefault();action("disputes",{reason_code:reason,description})}}><label>Причина<CustomSelect required value={reason} onChange={e=>setReason(e.target.value)}><option value="">Выберите</option><option value="WORK_NOT_DELIVERED">Работа не передана</option><option value="WORK_DOES_NOT_MATCH_SCOPE">Результат не соответствует заданию</option><option value="CUSTOMER_UNRESPONSIVE">Заказчик не отвечает</option><option value="OTHER">Другое</option></CustomSelect></label><label>Описание<textarea required minLength={3} maxLength={5000} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="button button--danger">Открыть спор</button></form></details></section>:null}
    </div><aside className="deal-actions"><h2>Следующее действие</h2>{d.viewer_role==="CUSTOMER"&&d.status==="AWAITING_FUNDING"&&!d.payment?.checkout_url?<button onClick={()=>action("fund")}>{d.payment?"Повторить создание оплаты":"Перейти к оплате"}</button>:null}{d.viewer_role==="CUSTOMER"&&d.status==="AWAITING_FUNDING"&&d.payment?.checkout_url?<a className="button" href={d.payment.checkout_url}>Продолжить оплату</a>:null}{d.viewer_role==="FREELANCER"&&d.status==="FUNDED"?<button onClick={()=>action("start")}>Начать работу</button>:null}{d.viewer_role==="CUSTOMER"&&d.status==="AWAITING_FUNDING"?<button className="button button--danger" onClick={()=>action("cancel")}>Отменить сделку</button>:null}{d.viewer_role==="CUSTOMER"&&d.status==="FUNDED"?<button className="button button--danger" onClick={()=>action("cancel")}>Отменить и вернуть средства</button>:null}{d.conversation_id?<a className="button button--quiet" href={`/messages?conversation=${encodeURIComponent(d.conversation_id)}`}>Открыть чат</a>:null}<p className="card-meta">Все финансовые команды идемпотентны, а спор блокирует автоматический расчёт.</p></aside></div>
  </main>;
}
