"use client";
import { CustomSelect } from "../../custom-select";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AdminError, AdminHeader, AdminLoading, AdminPager, AdminReasonAction, AdminTable, StatusPill, adminRequest, capabilityText, compactID, formatDate, roleText } from "../admin-ui";

type User = { id:string; email:string; username?:string; display_name:string; status:string; email_verified:boolean; roles:string[]; capabilities:string[]; created_at:string; last_seen_at?:string; active_sessions:number };
type Page = { next_cursor?:string|null; has_more:boolean };
export default function UsersPage(){
  const [items,setItems]=useState<User[]>([]),[page,setPage]=useState<Page>({has_more:false}),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const [q,setQ]=useState(""),[status,setStatus]=useState(""),[role,setRole]=useState("");
  const load=useCallback(async(cursor?:string,append=false)=>{setLoading(true);setError("");try{const params=new URLSearchParams({limit:"30"});if(q)params.set("q",q);if(status)params.set("status",status);if(role)params.set("role",role);if(cursor)params.set("cursor",cursor);const body=await adminRequest<{data:User[];page:Page}>(`/api/v1/admin/users?${params}`);setItems(v=>append?[...v,...body.data]:body.data);setPage(body.page)}catch(e){setError(e instanceof Error?e.message:"Ошибка") }finally{setLoading(false)}},[q,status,role]);
  useEffect(()=>{load()},[load]);
  function submit(e:FormEvent){e.preventDefault();load()}
  return <><AdminHeader title="Пользователи" description="Учётные записи, роли, статусы и активные сессии. Все чувствительные изменения требуют причины и попадают в аудит."/>
    <form className="admin-toolbar" onSubmit={submit}><input aria-label="Поиск" placeholder="Имя или email" value={q} onChange={e=>setQ(e.target.value)}/><CustomSelect aria-label="Статус" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Все статусы</option><option value="ACTIVE">Активные</option><option value="SUSPENDED">Приостановленные</option><option value="BANNED">Заблокированные</option><option value="DELETED">Удалённые</option></CustomSelect><CustomSelect aria-label="Роль" value={role} onChange={e=>setRole(e.target.value)}><option value="">Все роли</option><option value="MODERATOR">Модераторы</option><option value="ADMIN">Администраторы</option><option value="SUPER_ADMIN">Суперадминистраторы</option></CustomSelect><button>Найти</button></form>
    {error?<AdminError message={error} onRetry={()=>load()}/>:loading&&!items.length?<AdminLoading/>:<AdminTable columns={["Пользователь","Доступ","Статус","Активность","Действия"]} empty={!items.length}>{items.map(u=><tr key={u.id}><td><a className="admin-primary-link" href={`/x7m4q9k2/users/${u.id}`}>{u.display_name}</a><small>{u.email}</small><small>{compactID(u.id)}</small></td><td><div className="admin-tag-row">{u.roles.map(v=><span className="admin-tag admin-tag--role" key={v}>{roleText(v)}</span>)}{u.capabilities.map(v=><span className="admin-tag" key={v}>{capabilityText(v)}</span>)}</div></td><td><StatusPill value={u.status}/><small>{u.email_verified?"Email подтверждён":"Email не подтверждён"}</small></td><td><small>Создан: {formatDate(u.created_at)}</small><small>Сессий: {u.active_sessions}</small></td><td><div className="admin-row-actions">{u.status==="SUSPENDED"?<AdminReasonAction label="Возобновить" title={`Возобновить доступ: ${u.display_name}`} onConfirm={async reason=>{await adminRequest(`/api/v1/admin/users/${u.id}/status`,{method:"PATCH",body:JSON.stringify({status:"ACTIVE",reason})});load()}}/>:null}{u.status!=="SUSPENDED"&&u.status!=="BANNED"?<AdminReasonAction label="Приостановить" title={`Приостановить ${u.display_name}`} onConfirm={async reason=>{await adminRequest(`/api/v1/admin/users/${u.id}/status`,{method:"PATCH",body:JSON.stringify({status:"SUSPENDED",reason})});load()}}/>:null}{u.status!=="BANNED"?<AdminReasonAction label="Заблокировать" tone="danger" title={`Заблокировать ${u.display_name}`} onConfirm={async reason=>{await adminRequest(`/api/v1/admin/users/${u.id}/status`,{method:"PATCH",body:JSON.stringify({status:"BANNED",reason})});load()}}/>:<AdminReasonAction label="Разблокировать" title={`Разблокировать ${u.display_name}`} onConfirm={async reason=>{await adminRequest(`/api/v1/admin/users/${u.id}/status`,{method:"PATCH",body:JSON.stringify({status:"ACTIVE",reason})});load()}}/>}</div></td></tr>)}</AdminTable>}
    <AdminPager hasMore={page.has_more} loading={loading} onMore={()=>page.next_cursor&&load(page.next_cursor,true)}/>
  </>;
}
