import type { Metadata } from "next";
import { notFound } from "next/navigation";
import ApplicationForm from "../../vacancy/[id]/application-form";
import { canonical, jsonLD, missingMetadata, publicMetadata, summary } from "../../seo";
import { IconBriefcase, IconMapPin, IconWallet } from "../../icons";
import Breadcrumbs from "../../breadcrumbs";

export const dynamic = "force-dynamic";

type Vacancy={id:string;title:string;description:string;company?:{name:string;website?:string;description?:string;verification_status:string};customer_name?:string;employment_type:string;salary_min_kopecks?:number;salary_max_kopecks?:number;currency:string;remote:boolean;location?:string;experience_level?:string;skills:Array<{id:string;name:string}>;published_at?:string};
async function load(id:string):Promise<Vacancy|null>{const base=process.env.API_BASE_URL??"http://localhost:8080";const r=await fetch(`${base}/api/v1/vacancies/${encodeURIComponent(id)}`,{cache:"no-store"});if(r.status===404)return null;if(!r.ok)throw new Error("vacancy request failed");return (await r.json()).data??null;}
const money=(n?:number)=>n?new Intl.NumberFormat("ru-RU").format(n/100):"";
const employmentLabels:Record<string,string>={FULL_TIME:"Полная занятость",PART_TIME:"Частичная занятость",CONTRACT:"Контракт",INTERNSHIP:"Стажировка"};
const experienceLabels:Record<string,string>={JUNIOR:"Junior",MIDDLE:"Middle",SENIOR:"Senior",LEAD:"Lead",ANY:"Любой уровень",BEGINNER:"Начинающий",INTERMEDIATE:"Средний",ADVANCED:"Опытный",EXPERT:"Эксперт"};
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const v=await load(id);if(!v)return missingMetadata("Вакансия не найдена");return publicMetadata(`${v.title} — ${v.company?.name??v.customer_name??"работодатель"}`,summary(v.description,"Активная вакансия."),`/vacancies/${v.id}`)}
export default async function VacancyPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const v=await load(id);if(!v)notFound();const salary=v.salary_min_kopecks||v.salary_max_kopecks?{"@type":"MonetaryAmount",currency:"RUB",value:{"@type":"QuantitativeValue",minValue:v.salary_min_kopecks?v.salary_min_kopecks/100:undefined,maxValue:v.salary_max_kopecks?v.salary_max_kopecks/100:undefined,unitText:"MONTH"}}:undefined;const schema={"@context":"https://schema.org","@type":"JobPosting",title:v.title,description:summary(v.description,v.title,1000),datePosted:v.published_at,hiringOrganization:{"@type":"Organization",name:v.company?.name??v.customer_name??"Работодатель",sameAs:v.company?.website||undefined},employmentType:v.employment_type,jobLocationType:v.remote?"TELECOMMUTE":undefined,jobLocation:!v.remote&&v.location?{"@type":"Place",address:v.location}:undefined,baseSalary:salary,url:canonical(`/vacancies/${v.id}`)};return <main><Breadcrumbs items={[{label:"Главная",href:"/"},{label:"Вакансии",href:"/vacancies"},{label:v.title}]}/><header className="vacancy-detail-hero"><div className="vacancy-detail-logo"><IconBriefcase size={30}/><span>{(v.company?.name??v.customer_name??"Naimio").slice(0,2).toUpperCase()}</span></div><div><p className="eyebrow">{v.company?.name??v.customer_name??"Работодатель"}</p><h1>{v.title}</h1><p className="vacancy-detail-meta"><span><IconBriefcase size={16}/>{employmentLabels[v.employment_type]??v.employment_type}</span><span><IconMapPin size={16}/>{v.remote?"Удалённо":v.location||"На месте"}</span>{v.salary_min_kopecks||v.salary_max_kopecks?<span><IconWallet size={16}/>{v.salary_min_kopecks?`от ${money(v.salary_min_kopecks)}`:""}{v.salary_max_kopecks?` до ${money(v.salary_max_kopecks)}`:""} ₽</span>:null}</p></div></header><section><h2>Описание вакансии</h2><p>{v.description}</p></section>{v.skills.length?<section><h2>Навыки</h2><ul>{v.skills.map(s=><li key={s.id}>{s.name}</li>)}</ul></section>:null}<section><h2>Условия</h2><p>{v.salary_min_kopecks||v.salary_max_kopecks?`${v.salary_min_kopecks?`от ${money(v.salary_min_kopecks)}`:""}${v.salary_max_kopecks?` до ${money(v.salary_max_kopecks)}`:""} ₽`:"Зарплата по договорённости"}</p>{v.experience_level?<p>Опыт: {experienceLabels[v.experience_level]??v.experience_level}</p>:null}</section>{v.company&&(v.company.description||v.company.website)?<section><h2>Компания</h2>{v.company.description?<p>{v.company.description}</p>:null}{v.company.website?<p><a href={v.company.website} rel="nofollow noopener noreferrer">Сайт компании</a></p>:null}</section>:null}<ApplicationForm vacancyId={v.id}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLD(schema)}}/></main>}
