"use client";

import { useEffect, useRef, useState } from "react";
import Breadcrumbs from "../../breadcrumbs";

type Binding={provider:string;status:string;masked_destination?:string;setup_kind:string;account_id?:string};
type WidgetResult={payout_token:string;first6:string;last4:string;issuer_name:string;issuer_country:string;card_type:string};
type PayoutWidget={render:(id:string)=>Promise<void>;clearListeners?:()=>void};
type PayoutWidgetCtor=new (options:{type:string;account_id:string;success_callback:(data:WidgetResult)=>void;error_callback:()=>void})=>PayoutWidget;
declare global{interface Window{PayoutsData?:PayoutWidgetCtor}}

const statusText:Record<string,string>={NOT_CONFIGURED:"Не настроено",PENDING_VERIFICATION:"Проверяется",VERIFIED:"Готово к выплате",REJECTED:"Требуется действие",DISABLED:"Отключено"};

export default function PayoutsPage(){
  const[binding,setBinding]=useState<Binding|null>(null),[error,setError]=useState(""),[unavailable,setUnavailable]=useState(false),[busy,setBusy]=useState(false);
  const widget=useRef<PayoutWidget|null>(null);
  async function load(){const r=await fetch("/api/v1/me/payout-recipient",{credentials:"same-origin",cache:"no-store"});const b=await r.json().catch(()=>null);if(!r.ok){if(b?.error?.code==="PAYOUT_UNAVAILABLE"){setUnavailable(true);setError("");return}throw new Error(b?.error?.message||"Не удалось загрузить реквизиты")}setUnavailable(false);setBinding(b.data)}
  async function save(data:WidgetResult){setBusy(true);setError("");try{const r=await fetch("/api/v1/me/payout-recipient",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error?.message||"Не удалось сохранить реквизиты");setBinding(b.data)}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить реквизиты")}finally{setBusy(false)}}
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Не удалось загрузить реквизиты"))},[]);
  useEffect(()=>{if(!binding||binding.provider!=="yookassa"||binding.setup_kind!=="YOOKASSA_PAYOUT_WIDGET"||!binding.account_id||binding.status==="VERIFIED")return;let active=true;const boot=()=>{if(!active||!window.PayoutsData||!binding.account_id)return;widget.current?.clearListeners?.();widget.current=new window.PayoutsData({type:"safedeal",account_id:binding.account_id,success_callback:(data)=>{void save(data)},error_callback:()=>setError("Не удалось получить защищённый токен карты. Проверьте данные и попробуйте ещё раз.")});widget.current.render("yookassa-payout-widget").catch(()=>setError("Не удалось загрузить форму ЮKassa."))};const existing=document.querySelector<HTMLScriptElement>('script[data-yookassa-payout-widget="true"]');if(existing){if(window.PayoutsData)boot();else existing.addEventListener("load",boot,{once:true})}else{const script=document.createElement("script");script.src="https://yookassa.ru/payouts-data/3.1.0/widget.js";script.async=true;script.dataset.yookassaPayoutWidget="true";script.addEventListener("load",boot,{once:true});script.addEventListener("error",()=>setError("Не удалось загрузить защищённую форму ЮKassa."),{once:true});document.head.appendChild(script)}return()=>{active=false;widget.current?.clearListeners?.()}},[binding]);
  return <main><Breadcrumbs items={[{label:"Главная",href:"/"},{label:"Кабинет",href:"/dashboard"},{label:"Выплаты"}]}/><div className="page-heading"><div><p className="eyebrow">Safe Deal</p><h1>Реквизиты для выплат</h1><p className="lead">Данные карты вводятся в защищённой форме платёжного провайдера. Naimio хранит только безопасный токен и маску карты — не номер карты и не CVV.</p></div></div>{error?<div className="error" role="alert">{error}</div>:null}{unavailable?<section className="notice"><h2>Платёжный провайдер для выплат ещё не настроен</h2><p>Функция выплат реализована, но для защищённой формы нужны активированные реквизиты Safe Deal-провайдера. После настройки провайдера форма появится здесь автоматически.</p></section>:!binding?<div className="skeleton skeleton--card"/>:<section className="deal-panel"><div className="section-heading"><div><p className="eyebrow">{binding.provider}</p><h2>{statusText[binding.status]||binding.status}</h2></div>{binding.masked_destination?<span className="badge">{binding.masked_destination}</span>:null}</div>{binding.status==="VERIFIED"?<><p>Реквизиты готовы для выплат по завершённым Safe Deal.</p><button className="button button--quiet" disabled={busy} onClick={()=>setBinding({...binding,status:"NOT_CONFIGURED",masked_destination:undefined})}>Изменить реквизиты</button></>:binding.provider==="yookassa"&&binding.account_id?<><p>Введите карту в форме ЮKassa. После успешной токенизации номер карты не передаётся на сервер Naimio.</p><div id="yookassa-payout-widget" aria-busy={busy}/></>:<p>Для выбранного провайдера защищённая настройка выплат пока недоступна в текущей конфигурации. Обратитесь в поддержку.</p>}</section>}</main>;
}
