import Breadcrumbs from "../breadcrumbs";
import { IconArrowRight, IconChart, IconCode, IconMegaphone } from "../icons";
import { publicMetadata } from "../seo";
export const metadata=publicMetadata("Калькуляторы стоимости","Проверенные калькуляторы дают реалистичный диапазон и сохраняют ответы в черновик проекта.","/price");
type Item={slug:string;title:string;intro:string};
const fallback:Item[]=[{slug:"telegram-bot",title:"Стоимость Telegram-бота",intro:"Сценарии, интеграции и панель управления"},{slug:"landing-page",title:"Стоимость лендинга",intro:"Дизайн, смысловые блоки и подготовка текстов"},{slug:"seo",title:"Стоимость SEO-продвижения",intro:"Размер сайта, конкуренция и производство контента"}];
async function load():Promise<Item[]>{try{const base=process.env.API_BASE_URL??"http://localhost:8080";const response=await fetch(`${base}/api/v1/calculators`,{next:{revalidate:300}});if(response.ok){const body=await response.json();if(Array.isArray(body.data))return body.data}}catch{}return fallback}
function icon(slug:string){if(slug.includes("seo")||slug.includes("market"))return <IconMegaphone size={26}/>;if(slug.includes("landing")||slug.includes("design"))return <IconChart size={26}/>;return <IconCode size={26}/>}
export default async function Price(){const items=await load();return <main className="price-index"><Breadcrumbs items={[{label:"Главная",href:"/"},{label:"Калькуляторы"}]}/><header className="page-heading"><div><p className="eyebrow">Ориентир до публикации</p><h1>Калькуляторы стоимости</h1><p className="lead">Выберите тип задачи и получите реалистичный диапазон без обещаний точной цены до знакомства с заданием.</p></div></header><div className="calculator-index-grid">{items.map(item=><a className="calculator-index-card" href={`/price/${item.slug}`} key={item.slug}><span className="calculator-index-card__icon">{icon(item.slug)}</span><div><h2>{item.title}</h2><p>{item.intro}</p></div><IconArrowRight size={20}/></a>)}</div></main>}
