"use client";

import { CustomSelect } from "../../custom-select";
import { FormEvent, useMemo, useRef, useState } from "react";
import { attribution, track } from "../../analytics";
import { IconCheck, IconClock, IconTag, IconWallet } from "../../icons";

type Option={value:string;label:string};type Question={key:string;label:string;type:"SELECT"|"NUMBER"|"BOOLEAN";required:boolean;min?:number;max?:number;options?:Option[]};type Definition={slug:string;title:string;version:number;questions:Question[]};type Result={estimated_min_kopecks:number;estimated_max_kopecks:number;currency:string;estimated_duration_days:{min:number;max:number};recommended_category?:{name:string};recommended_skills:Array<{name:string}>;assumptions:string[];confidence:string;draft_token:string};
const money=(value:number)=>new Intl.NumberFormat("ru-RU",{maximumFractionDigits:0}).format(value/100);

export default function Calculator({definition}:{definition:Definition}){
  const initial=useMemo(()=>Object.fromEntries(definition.questions.map(q=>[q.key,q.type==="SELECT"?q.options?.[0]?.value??"":q.type==="NUMBER"?q.min??0:false])),[definition]);
  const[answers,setAnswers]=useState<Record<string,string|number|boolean>>(initial);const[result,setResult]=useState<Result|null>(null);const[state,setState]=useState("");const[busy,setBusy]=useState(false);const started=useRef(false);
  function begin(){if(!started.current){started.current=true;track("CALCULATOR_STARTED",{calculator_slug:definition.slug})}}
  async function submit(e:FormEvent){e.preventDefault();begin();setBusy(true);setState("Считаем реалистичный диапазон…");setResult(null);try{const response=await fetch(`/api/v1/calculators/${definition.slug}/estimate`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers,attribution:attribution()})});if(!response.ok)throw new Error();setResult((await response.json()).data);setState("Расчёт готов.")}catch{setState("Не удалось рассчитать. Проверьте ответы и попробуйте снова.")}finally{setBusy(false)}}
  return <div className="calculator-workspace"><form className="calculator-form" onSubmit={submit} onChange={begin}><div className="calculator-form__heading"><span>01</span><div><h2>Параметры задачи</h2><p>Изменяйте ответы — итог можно пересчитать.</p></div></div>{definition.questions.map((q,index)=><div className={`calculator-field calculator-field--${q.type.toLowerCase()}`} key={q.key}><span className="calculator-field__number">{String(index+1).padStart(2,"0")}</span>{q.type==="BOOLEAN"?<label className="calculator-switch"><span><strong>{q.label}</strong><small>Включите, если это требуется в проекте</small></span><input type="checkbox" checked={Boolean(answers[q.key])} onChange={e=>setAnswers({...answers,[q.key]:e.target.checked})}/><i aria-hidden="true"/></label>:<label><strong>{q.label}</strong>{q.type==="SELECT"?<CustomSelect required={q.required} value={String(answers[q.key])} onChange={e=>setAnswers({...answers,[q.key]:e.target.value})}>{q.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</CustomSelect>:<input type="number" required={q.required} min={q.min} max={q.max} value={Number(answers[q.key])} onChange={e=>setAnswers({...answers,[q.key]:Number(e.target.value)})}/>}</label>}</div>)}<button className="calculator-submit" disabled={busy}>{busy?<><span className="spinner"/>Считаем…</>:<>Рассчитать диапазон <span aria-hidden="true">→</span></>}</button><p className="calculator-state" role="status">{state}</p></form>
  <aside className={`calculator-result${result?" is-ready":""}`} aria-live="polite">{result?<><p className="eyebrow">Предварительная оценка</p><h2>Ориентировочная стоимость</h2><strong className="calculator-result__price">{money(result.estimated_min_kopecks)}–{money(result.estimated_max_kopecks)} ₽</strong><p className="calculator-result__note">Диапазон учитывает выбранные параметры, но не заменяет предложение исполнителя.</p><div className="calculator-result__facts"><span><IconClock size={18}/><small>Срок</small><strong>{result.estimated_duration_days.min}–{result.estimated_duration_days.max} дней</strong></span>{result.recommended_category?<span><IconTag size={18}/><small>Категория</small><strong>{result.recommended_category.name}</strong></span>:null}</div>{result.recommended_skills.length?<div className="calculator-result__skills">{result.recommended_skills.map(value=><span key={value.name}>{value.name}</span>)}</div>:null}{result.assumptions.length?<div className="calculator-result__assumptions"><h3>Что учтено</h3><ul>{result.assumptions.map(value=><li key={value}><IconCheck size={15}/>{value}</li>)}</ul></div>:null}<a className="button calculator-result__cta" href={`/create-project?draft=${result.draft_token}`}>Получить реальные предложения</a></>:<><span className="calculator-result__placeholder-icon"><IconWallet size={30}/></span><h2>Здесь появится результат</h2><p>Заполните параметры слева. Покажем диапазон стоимости, срок и подходящие навыки.</p><div className="calculator-result__placeholder-bars"><span/><span/><span/></div></>}</aside></div>;
}
