import Breadcrumbs from "../../breadcrumbs";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Calculator from "./calculator";
import { jsonLD, missingMetadata, publicMetadata, summary } from "../../seo";
type Definition={slug:string;title:string;intro:string;version:number;questions:Array<{key:string;label:string;type:"SELECT"|"NUMBER"|"BOOLEAN";required:boolean;min?:number;max?:number;options?:Array<{value:string;label:string}>}>;updated_at:string};
const slugs=["telegram-bot","landing-page","seo"];
const fallback:Record<string,Definition>={
  "telegram-bot":{slug:"telegram-bot",title:"Стоимость Telegram-бота",intro:"Оцените разработку Telegram-бота по функциям и интеграциям.",version:1,updated_at:"2026-01-01T00:00:00Z",questions:[{key:"complexity",label:"Сценарий",type:"SELECT",required:true,options:[{value:"basic",label:"Простой информационный"},{value:"workflow",label:"Бизнес-процесс"},{value:"commerce",label:"Продажи и оплаты"}]},{key:"integrations",label:"Количество интеграций",type:"NUMBER",required:true,min:0,max:10},{key:"admin",label:"Нужна панель управления",type:"BOOLEAN",required:true}]},
  "landing-page":{slug:"landing-page",title:"Стоимость лендинга",intro:"Рассчитайте диапазон стоимости лендинга без ложной точности.",version:1,updated_at:"2026-01-01T00:00:00Z",questions:[{key:"design",label:"Дизайн",type:"SELECT",required:true,options:[{value:"template",label:"На основе шаблона"},{value:"custom",label:"Индивидуальный"}]},{key:"sections",label:"Количество смысловых блоков",type:"NUMBER",required:true,min:3,max:20},{key:"copywriting",label:"Нужны тексты",type:"BOOLEAN",required:true}]},
  seo:{slug:"seo",title:"Стоимость SEO-продвижения",intro:"Оцените стартовый диапазон SEO-работ по размеру сайта и конкуренции.",version:1,updated_at:"2026-01-01T00:00:00Z",questions:[{key:"site_size",label:"Размер сайта",type:"SELECT",required:true,options:[{value:"small",label:"До 50 страниц"},{value:"medium",label:"50–500 страниц"},{value:"large",label:"Более 500 страниц"}]},{key:"competition",label:"Конкуренция",type:"SELECT",required:true,options:[{value:"low",label:"Низкая"},{value:"medium",label:"Средняя"},{value:"high",label:"Высокая"}]},{key:"content",label:"Нужно производство контента",type:"BOOLEAN",required:true}]}
};
export function generateStaticParams(){return slugs.map(slug=>({slug}))}
async function load(slug:string):Promise<Definition|null>{if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))return null;try{const base=process.env.API_BASE_URL??"http://localhost:8080";const response=await fetch(`${base}/api/v1/calculators/${slug}`,{next:{revalidate:300}});if(response.ok)return (await response.json()).data??fallback[slug]??null;return fallback[slug]??null}catch{return fallback[slug]??null}}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const d=await load(slug);if(!d)return missingMetadata("Калькулятор не найден");return publicMetadata(d.title,summary(d.intro,"Рассчитайте ориентировочный диапазон стоимости и создайте проект без повторного ввода."),`/price/${d.slug}`)}
export default async function CalculatorPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=await load(slug);if(!d)notFound();const data={"@context":"https://schema.org","@type":"WebApplication",name:d.title,description:d.intro,applicationCategory:"BusinessApplication",operatingSystem:"Web",isAccessibleForFree:true};return <main className="calculator-page"><Breadcrumbs items={[{label:"Главная",href:"/"},{label:"Калькуляторы",href:"/price"},{label:d.title}]}/><header className="calculator-hero"><p className="eyebrow">Калькулятор стоимости</p><h1>{d.title}</h1><p className="lead">{d.intro}</p><span>Без AI и ложной точности · результат не является офертой</span></header><Calculator definition={d}/><aside className="calculator-explainer"><h2>Как понимать результат</h2><p>Диапазон помогает сформировать ожидания. Финальные условия зависят от подробного задания, сроков и предложений специалистов.</p></aside><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLD(data)}}/></main>}
