"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { AdminEntityLink,AdminError,AdminHeader,AdminLoading,AdminPager,AdminReasonAction,AdminRichText,AdminTable,StatusPill,adminRequest,formatDate } from "./admin-ui";
type Item={id:string;kind:string;title:string;owner_user_id:string;owner_display_name:string;status:string;moderation_status:string;moderation_reason?:string;category_name?:string;created_at:string;updated_at:string};type Page={next_cursor?:string|null;has_more:boolean};
export default function ContentAdmin({endpoint,title,description}:{endpoint:"projects"|"services"|"vacancies";title:string;description:string}){
 const[items,setItems]=useState<Item[]>([]),[page,setPage]=useState<Page>({has_more:false}),[q,setQ]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async(cursor?:string,append=false)=>{setLoading(true);setError("");try{const p=new URLSearchParams({limit:"30"});if(q)p.set("q",q);if(status)p.set("status",status);if(cursor)p.set("cursor",cursor);const b=await adminRequest<{data:Item[];page:Page}>(`/api/v1/admin/${endpoint}?${p}`);setItems(v=>append?[...v,...b.data]:b.data);setPage(b.page)}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setLoading(false)}},[endpoint,q,status]);
 useEffect(()=>{load()},[load]); function submit(e:FormEvent){e.preventDefault();load()}
 async function moderate(item:Item,action:"HIDE"|"RESTORE"|"REJECT"|"DELETE",reason:string){await adminRequest(`/api/v1/admin/${endpoint}/${item.id}/moderation`,{method:"POST",body:JSON.stringify({action,reason})});load()}
 return <><AdminHeader title={title} description={description}/><form className="admin-toolbar" onSubmit={submit}><input aria-label="Поиск" placeholder="Название или владелец" value={q} onChange={e=>setQ(e.target.value)}/><input aria-label="Статус" placeholder="Статус публикации" value={status} onChange={e=>setStatus(e.target.value.toUpperCase())}/><button>Применить</button></form>{error?<AdminError message={error} onRetry={()=>load()}/>:loading&&!items.length?<AdminLoading/>:<AdminTable columns={["Объект","Владелец","Статус","Модерация","Действия"]} empty={!items.length}>{items.map(x=>{const rejected=x.moderation_status==="HIDDEN"&&Boolean(x.moderation_reason)&&((x.kind==="PROJECT"||x.kind==="VACANCY")?x.status==="DRAFT":x.kind==="SERVICE"?x.status==="REJECTED":true);return <tr key={x.id}><td><AdminEntityLink entityType={x.kind} entityID={x.id} label={x.title}/><small>{x.category_name||x.kind}</small><small>{formatDate(x.created_at)}</small></td><td><AdminEntityLink entityType="USER" entityID={x.owner_user_id} label={x.owner_display_name}/></td><td><StatusPill value={x.status}/></td><td><StatusPill value={rejected?"REJECTED":x.moderation_status}/>{x.moderation_reason?<AdminRichText html={x.moderation_reason}/>:null}</td><td><div className="admin-row-actions">{x.moderation_status==="HIDDEN"&&!rejected?<AdminReasonAction label="Восстановить" title={`Восстановить: ${x.title}`} onConfirm={r=>moderate(x,"RESTORE",r)}/>:x.moderation_status!=="HIDDEN"?<AdminReasonAction label="Скрыть" title={`Скрыть: ${x.title}`} onConfirm={r=>moderate(x,"HIDE",r)}/>:null}{!rejected&&x.moderation_status!=="HIDDEN"?<AdminReasonAction label="Отклонить" tone="danger" title={`Отклонить: ${x.title}`} description="Владелец получит уведомление, email и системное сообщение поддержки." onConfirm={r=>moderate(x,"REJECT",r)}/>:null}<AdminReasonAction label="Удалить" tone="danger" title={`Удалить: ${x.title}`} description="Объект исчезнет с сайта. Решение и причина останутся в аудите, владелец получит уведомление." onConfirm={r=>moderate(x,"DELETE",r)}/></div></td></tr>})}</AdminTable>}<AdminPager hasMore={page.has_more} loading={loading} onMore={()=>page.next_cursor&&load(page.next_cursor,true)}/></>
}
